### ISSUE TITLE
Remove ITEMGROUPDATASEQ support

### ISSUE THREAD

**Issue by lexjansen** [lexjansen/dataset-json-sas#50]
To avoid confusion with the --SEQ variables, the Dataset-JSON development team decided to rename ITEMGROUPDATASEQ to ROWNUM.
However, upon further discussion within the team it was decided to remove ITEMGROUPDATASEQ from the Dataset-JSON specification altogether. 
As we are storing data in a JSON array, the element number (index) is something that is already automatically there when an application reads this array. In cases where order or a record identifier matters, the data being represented may already have an explicit record identifier, and/or set of keys.

**Comment by lattaai6** [comment]
Hello, I tried to fix the issue.

This is what I did:

Removed all references to ITEMGROUPDATASEQ in the write_datasetjson.sas macro. This includes removing the creation of the ITEMGROUPDATASEQ variable and associated metadata.

You can review changes in this commit: https://github.com/lattaai6/lexjansen-dataset-json-sas-50/commit/a8bdc8db304576d339b3715cf7096e36dd343ba4.


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This issue was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
